name: Criando nosso trigger deployment

on:
  deployment

jobs:
  job-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Printa deployment
        run: echo "Esse job foi triggado por um deployment externo"