name: Desafio 1

on: 
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Validação da imagem escolhida pelo usuário'
        required: true
        type: string


jobs:
  Desafio_1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Step1
      run: |
        docker pull ${{ github.event.inputs.imagename }}


    - name: Step2
      run: |
        IMAGE_NAME=$(echo "${{ github.event.inputs.imagename }}" | cut -d':' -f1)
        docker images | grep $IMAGE_NAME

    - name: Step3
      uses: docker/scout-action@v1
      with:
        command: quickview,cves,recomendations,sbom
        image: ${{ github.event.inputs.imagename }}
        only-severities: critital.high
        
        