name: Desafio 1

on: 
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Image Name'
        required: true
        type: string


jobs:
  Desafio_1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Step1
      run: docker pull ${{ inputs.imagename }}


    - name: Step2
      run: docker images


    - name: Step3
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ inputs.imagename }}
        summary: true
        