name: Workflow Run

on:
  workflow_run:
    workflows: [Chama Workflow Compartilhado]
    types:
      - completed

jobs:
  fala-o-nome-do-curso:
    runs-on: ubuntu-latest
    steps:
      - name: Informa o nome do curso
        run: echo "O Workflow Compartilhado 'Chama Workflow Compartilhado' terminou de ser executado."