name: Validação de Ambiente

on:
  workflow_dispatch:

jobs:
  valida-ambiente-prd:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Printa valor
        run: echo "Estou no ambiente ${{ vars.AMBIENTE }}"
  
  valida-ambiente-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Printa valor
        run: echo "Estou no ambiente ${{ vars.AMBIENTE }}"

