name: Valida o nome do PR

on:
  pull_request:
    types: [opened]

jobs:
  valida-nome-do-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o nome do PR
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ $title =- ^octocat ]]; then
          echo "PR title starts with 'octocat'"
          exit 0
          else
          echo "PR title does not start with 'octocat'"
          exit 1
          fi